### ISSUE TITLE
[Meta] Transition to Jenkins Pipeline

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#117]
This meta tracks the tickets needed to replace existing [job definitions](https://github.com/deis/jenkins-jobs) with in-repo [Jenkins Pipeline](https://gist.github.com/vdice/5961dbaf9ec8c3551fe3200f5f5a4ab3) representations:
- [ ] Transition first Workflow component repo to Jenkins Pipeline: https://github.com/deis/jenkins-jobs/issues/118
- [ ] Transition remaining Workflow component repos to using Jenkins Pipeline: https://github.com/deis/jenkins-jobs/issues/119
- [ ] Extract common logic used in Workflow component pipelines into the [Global DSL library](https://github.com/jenkinsci/workflow-cps-global-lib-plugin/blob/master/README.md): https://github.com/deis/jenkins-jobs/issues/120
- [ ] Document new Pipeline/Jenkinsfile approach and how to use in existing/new repos: https://github.com/deis/jenkins-jobs/issues/121
- [ ] Replace remaining (non-component) jobs in [jenkins-jobs](https://github.com/deis/jenkins-jobs) with Pipeline: https://github.com/deis/jenkins-jobs/issues/122

_Bonus/if still warranted_: Wrap up global DSL into 'official' Pipeline [plugin(s)](https://jenkins.io/blog/2016/04/21/dsl-plugins/)

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/jenkins-jobs#21
