### ISSUE TITLE
[Meta] <component>-tag-release job

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#158]
As part of the initiative to release a single component at a time (independent of Workflow as a whole) we require a `<component>-tag-release` job for each, which should:
1. watch for git push events to a refspec of `+refs/tags/*:refs/remotes/origin/tags/*` and branch `*/tags/*` (in essence, a tag push event)
2. determine if branch from above is indeed the latest tag, if so, proceed; if no, exit.
3. based on commit at HEAD of branch, find the correlating `git-<commit:0:7>` image tag (ref https://github.com/deis/jenkins-jobs/issues/155) in the 'deis' org of quay and use this for running/vetting in e2e tests
4. assuming e2e passes, retag image from above with 'pretty'/semver release tag (based on actual git tag pushed) in the quay.io and dockerhub 'deis' orgs

TODO for an iterative approach
- [x] create job covering steps 1. and 2. (https://github.com/deis/jenkins-jobs/pull/168)
- [x] promote prod-candidate images on master merge https://github.com/deis/jenkins-jobs/issues/155
- [x] once the e2e strategy is finalized, add step 3. and 4. to job (https://github.com/deis/jenkins-jobs/issues/169)

ref https://github.com/deis/workflow/pull/410

**Comment by mboersma** [comment]
> determine if branch from above is indeed the latest tag, if so, proceed; if no, exit.

Can't this step just build regardless of whether the tag is latest or not? That would cover the case where an older tag is intentionally force-pushed (shouldn't happen, but I'm not sure why we have to ignore it).

**Comment by mboersma** [comment]
Step 3) implies that <component>-release jobs are already publishing prod-candidate images to the deis/ org on success. Is that a separate task or done already?

**Comment by vdice** [comment]
> Step 3) implies that -release jobs are already publishing prod-candidate images to the deis/ org on success. Is that a separate task or done already?

@mboersma good point; description updated linking to task

**Comment by vdice** [comment]
> Can't this step just build regardless of whether the tag is latest or not?

@mboersma it could.  Note however that on a tag push event, our test job in https://ci.deis.io/job/controller-tag-release ran 3 times, one checking out `origin/tags/v2.0.0`, another `origin/tags/v2.1.0` and the last `origin/tags/v2.1.1` (the last being the actual most recent tag)  because of our branch wildcard specifier `*/tags/*`.  

We'd then have 3 builds running, 2 of which would have presumably already been released and may be re-vetted against a workflow chart that has later versions of other workflow components.  Thoughts?

ps not sure why it ran precisely 3 times, as you'll note in each job output that 14 tags were found.

**Comment by mboersma** [comment]
I guess checking that the tag is the most recent one could be a safeguard against an accidental (or malicious) force-push of an existing tag, and if that's the way to avoid running unnecessary jobs for "all tags," then great.

I was assuming the GitHub hook payload would contain the actual tag pushed, and that the Jenkins job could access that so it runs only the appropriate task. But I think you said it's not so simple, and if this is the best strategy then let's do it.
