### ISSUE TITLE
[Meta] Revise CI pipeline into smaller units

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#20]
This ticket tracks the work needed to revise the current CI pipeline for a given Deis component change into the following state:

![proposed_pipeline](https://cloud.githubusercontent.com/assets/9322017/14261848/d9fb71b2-fa6f-11e5-8f83-bbe529757052.png)
- [ ] Create `unit test` job DSL: https://github.com/deis/jenkins-jobs/issues/21
- [ ] Create `integration test` job DSL: https://github.com/deis/jenkins-jobs/issues/22
- [ ] ~~Create `claim cluster` job DSL: https://github.com/deis/jenkins-jobs/issues/23~~
- [ ] Modify current e2e test job DSL (`workflow_test.groovy`) to only run tests, afterwards kicking off the following two jobs concurrently: https://github.com/deis/jenkins-jobs/issues/26
- [ ] ~~Create `cluster cleanup` job DSL: https://github.com/deis/jenkins-jobs/issues/24~~
- [ ] Create `chart bumpver` job DSL: https://github.com/deis/jenkins-jobs/issues/25

TODO
- [ ] Create actual visual/graphic of pipeline for each component

**Comment by vdice** [comment]
@jchauncey I'll let you update/revise and or even close (provided a new similar ticket is created) as I'm assuming the envisioned pipeline has changed with the recent k8s-claimer/e2e-runner work... for now, moving on to the `v2.0` milestone.

**Comment by vdice** [comment]
This pipeline vision has been superseded by work in [e2e-runner](https://github.com/deis/e2e-runner) and [k8s-claimer](https://github.com/deis/k8s-claimer).  We can revisit adding unit/integration jobs at a latter date when deemed appropriate.

**Comment by jchauncey** [comment]
my goal is to start working on a prototype of this soon
