### ISSUE TITLE
[Meta] Transition Workflow and component pipelines to supporting use of Kubernetes Helm charts

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#286]
Workflow and component pipelines (and various other moving parts) need modifications to support the use of Kubernetes Helm charts.  The long-term goal is to remove support for the Helm Classic charts altogether, as we transition to the official Helm.

### e2e-runner updates: 

- [x] Update [e2e-runner](https://github.com/deis/e2e-runner) logic to run `--set <component>.docker_tag=git-<short sha for commit>` for any/every `<COMPONENT>_GIT_TAG` set in the environment.  (See [here](https://github.com/deis/e2e-runner/blob/master/scripts/functions.sh) for context around the logic setting the vars) (https://github.com/deis/e2e-runner/pull/61)

- [x] Update logic [here](https://github.com/deis/e2e-runner/blob/master/scripts/run.sh#L31) so to remove hard-coded `workflow-dev` chart repo in favor of a configurable env var (say, `$CHART_REPO`) so that it may be `workflow-pr`, `workflow-staging`, etc. (https://github.com/deis/e2e-runner/pull/60)

- [x] ~~Add `WORKFLOW` to this [list](https://github.com/deis/e2e-runner/blob/master/scripts/config.sh#L38) so that a `WORKFLOW_SHA` env var can be detected and used (see below in deis/workflow PR case)~~ Not needed
 
### Workflow pipeline updates:
- [x] Update the [workflow chart pipeline](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_chart_pipeline.groovy) with the following:
    - [x] Prefix the latest tag for each component with `>=` to enable matching within a range, if repo is `workflow-dev` (Note: depends on https://github.com/kubernetes/helm/issues/1351) (https://github.com/deis/jenkins-jobs/pull/288)
  * Is there a change to the `charts` subdirectory?  If Yes:
    - [x] PR commit?: (https://github.com/deis/jenkins-jobs/pull/294)
      * Package and push `workflow-<version>+<git sha>.tgz` tarfile to the `workflow-pr` chart repo/bucket
      * kick off downstream e2e job specifying `CHART_REPO_TYPE=pr` and `WORKFLOW_SHA=<git sha>`
    - [x] Master commit: (https://github.com/deis/jenkins-jobs/pull/288)
      * Package and push `workflow-<version>-<timestamp>+<git sha>.tgz` tarfile to the `workflow-dev` chart repo/bucket
      * kick off downstream e2e job specifying `CHART_REPO_TYPE=dev`
  * if No (no change to `charts` subdirectory):
    * no changes needed at this time

### Component pipeline updates:

- [x] Update [component](https://github.com/deis/jenkins-jobs/blob/master/jobs/component_jobs.groovy) build jobs with the following:
  * Is there a change to the `charts` subdirectory?  If Yes:
    - [x] PR commit: (https://github.com/deis/jenkins-jobs/pull/294)
      * Package and push `<component>-<version>+<git sha>.tgz` tarfile to the `<component>-pr` chart repo/bucket
      * **Needs work** kick off downstream [workflow-dev-chart-publish](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_chart_pipeline.groovy#L9-L151) job which, with modifications to be mentioned above, will fetch this latest chart via `helm dependency update` and pass on to the e2e job 
    - [x] Master commit: (https://github.com/deis/jenkins-jobs/pull/288)
      * Package and push `<component>-<version>-(<timestamp>)+<git sha>.tgz` tarfile to the `<component>-dev` (staging) chart repo/bucket
      * kick off downstream [workflow-dev-chart-publish](https://github.com/deis/jenkins-jobs/blob/master/jobs/workflow_chart_pipeline.groovy#L9-L151) job which, with modifications mentioned above, will fetch this latest chart via `helm dependency update` and pass on to the e2e job
  * if No (no change to `charts` subdirectory):
    * no changes needed at this time, aside from the aforementioned e2e-runner changes
