### ISSUE TITLE
[Meta] Eliminate use of TravisCI for component repos

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#343]
In order to eliminate use of TravisCI and bring logic into Jenkins, a component repo...
 * MUST have containerized `make test` target (or dummy added a la `@echo "No unit tests implemented"`)

 * SHOULD have containerized `make test-cover` target

Current status of repos:

**Complies**
builder
controller (as of https://github.com/deis/controller/pull/1271 _merged_)
dockerbuilder (as of https://github.com/deis/dockerbuilder/pull/120 _merged_)
fluentd
logger
minio
redis
registry-token-refresher
router
slugbuilder
slugrunner
workflow-manager

**Kinda sorta complies**
jenkins-node (`test` just invokes `build` target) https://github.com/deis/jenkins-node/pull/7 _merged_
postgres (requires `make docker-build` before `make test`)
registry (requires `make docker-build` before `make test`)

**Does not yet comply**
~~dockerbuilder (py-based, not yet containerized)~~
e2e-runner (`test` is non-containerized, but `docker-test` is) https://github.com/deis/e2e-runner/pull/93 _merged_
nsq (no `test` target) https://github.com/deis/nsq/pull/16 _merged_
monitor/[grafana/influxdb/telegraf] (no `test` target) https://github.com/deis/nsq/pull/17 _merged_
workflow-e2e (no `test` target but does have `docker-test-style` which could be used) https://github.com/deis/workflow-e2e/pull/353 _merged_

TODO:
 - [x] ensure all component repos listed achieve compliance ~~(**edit:** PRs linked above are in flight)~~
 - [x] PR in this project adding necessary logic to `component_jobs.groovy` (**edit:** https://github.com/deis/jenkins-jobs/pull/373)
 - [x] once above two are completed and merged, issue PRs in all component repos removing `.travis.yml`, any associated scripts and updating Build Status link in `README.md` if applicable
 - [x] once PRs above merged, remove the `Travis CI` service for each repo; this can be done via https://github.com/deis/builder/settings/installations for example

**Comment by vdice** [comment]
This is now complete!
