### ISSUE TITLE
[Meta] Build jenkins cluster using Kubernetes 

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#40]
Let's bring up Jenkins 2.0 host+slaves on a k8s cluster as part of the effort to 'Sip our own champagne'.  Learnings from this 'Spike' will inform how best to move forward with a Jenkins Champagne cluster.

Thinking a combo of a [Jenkins Master Docker container](https://hub.docker.com/_/jenkins/), a handful of [Jenkins Slave Docker containers](https://hub.docker.com/r/csanchez/jenkins-slave/) and this [Jenkins K8s Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin), plus perhaps creating a Jenkins [Helm](https://github.com/helm/helm) chart...

**Comment by jchauncey** [comment]
## Where would we build this?

GKE. It's where we are already migrating most of our infrastructure so why not continue to use it. 

## What size nodes

`n1-standard-2` is probably a good place to start 

## How many nodes

5 nodes to start with is probably plenty. We can easily increase this just by scaling the cluster.

**Comment by jchauncey** [comment]
## Things we need to figure out
- [ ] - What does a slave image look like?
- [ ] - How do we keep slave images up to date?
- [ ] - How do we secure the cluster?

**Comment by jchauncey** [comment]
clearing this milestone for now

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/jenkins-jobs#26
