### ISSUE TITLE
[meta] Release Automation Improvements

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#55]
Our release process is still a highly manual process.  This ticket attempts to list/track items for improving said process.
- [x] replace values that change with each release with template values https://github.com/deis/charts/pull/228
- [x] add CHANGELOG.md generator https://github.com/deis/docker-go-dev/pull/35
- [ ] ~~jenkins job for testing (release) chart pr: https://github.com/deis/jenkins-jobs/issues/48~~
- [x] workflow-test-release jenkins job https://github.com/deis/jenkins-jobs/pull/68
- [x] automate release chart(s) creation https://github.com/deis/deisrel/issues/1
  
  _(more to come)_

**Comment by arschles** [comment]
More stuff:
- Identify the commit sha on each repo for the release
- Generate changelogs for each project
  - And automatically opening a pull request on each repo
  - When each PR is merged, the release commit sha should be updated
- Re-tag Docker images for the release
- Create and push git tags on each repo

**Comment by mboersma** [comment]
Progress has been made, but this is an ongoing meta issue, so I'm bumping it to [v2.0-beta4](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+user%3Adeis+milestone%3Av2.0-beta4).

**Comment by bacongobbler** [comment]
Other things we can add to the meta list:
- update the [release checklist](http://docs-v2.readthedocs.io/en/latest/roadmap/release-checklist/) with the new release workflow
- automate tagging and pushing `deisci/<component>:git-asdf123` to `quay.io/deis/<component>:$RELEASE` via [deis-workflow-group](https://github.com/deis/deis-workflow-group) (step 4 in the release checklist)
- automate step 8, using [seed-repo](https://github.com/deis/seed-repo) to [close a milestone](https://github.com/deis/seed-repo/pull/11).

**Comment by vdice** [comment]
The specific tasks listed in the description have been completed. 

Further release automation issues/improvements should be tracked in https://github.com/deis/deisrel
