### ISSUE TITLE
[Meta] Transfer component build/deploy steps from Travis to Jenkins

### ISSUE THREAD

**Issue by vdice** [deis/jenkins-jobs#57]
As we move our CI infrastructure to Jenkins, less functionality will be needed in Travis.  Eventually, we are planning to cease the dependence on Travis entirely, but this ticket tracks the reduced scope of moving build and deploy steps for master commits to Jenkins.

Add build/deploy steps to Jenkins component_job(s):
- [x] https://github.com/deis/jenkins-jobs/pull/56

Remove Travis build/deploy steps from components:
- [x] controller https://github.com/deis/controller/pull/645
- [x] postgres https://github.com/deis/postgres/pull/91
- [x] builder https://github.com/deis/builder/pull/303
- [x] logger https://github.com/deis/logger/pull/69
- [x] router https://github.com/deis/router/pull/166
- [x] workflow-manager https://github.com/deis/workflow-manager/pull/27
- [x] registry https://github.com/deis/registry/pull/41
- [x] minio https://github.com/deis/minio/pull/93
- [x] slugrunner https://github.com/deis/slugrunner/pull/33
- [x] slugbuilder https://github.com/deis/slugbuilder/pull/62
- [x] dockerbuilder https://github.com/deis/dockerbuilder/pull/50
- [x] fluentd https://github.com/deis/fluentd/pull/19
