### ISSUE TITLE
[meta] - Productionalize k8s claimer for deis ci 

### ISSUE THREAD

**Issue by jchauncey** [deis/jenkins-jobs#62]
- [ ] - Run k8s claimer on master ci node
- [ ] - Lock down port so only internal CI nodes can access
- [ ] - Install k8s claimer cli on all CI nodes

**Comment by jchauncey** [comment]
closing in favor of how we were deploying this with a little auth sprinkled in.
